apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
  # for more information on the below annotation, please see
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: samplecontroller.k8s.io
  versions:
    - name: v1alpha1
      served: true # 是否被服务
      storage: true # 是否被存储
      schema: # 用于验证资源的模式
        # schema used for validation
        openAPIV3Schema: # OpenAPI v3 模式
          type: object
          properties: # 定义资源的属性
            spec: # 定义资源的规格
              type: object
              properties:
                deploymentName:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status: # 定义资源的状态
              type: object
              properties:
                availableReplicas: # 可用的副本数，是一个整形
                  type: integer
  names: # 定义资源的名称
    kind: Foo
    plural: foos # 复数形式，k8s很多操作都是使用的复数形式
  scope: Namespaced  # 表示该资源在命名空间范围内可用
